source "http://rubygems.org"
gem "sinatra", :require => "sinatra/base"
gem "sinatra-flash", :require => "sinatra/flash"
gem "rack"
gem "rack-rewrite", :require => "rack/rewrite"
gem "haml"
gem "compass"
gem "mongoid"
gem "bson_ext"
gem 'prawn'
gem "rdiscount"
