trst_public:
  home:
    order: 1
    name_translations:
      ro: Prima pagină
      en: Home
      hu: Kezdő oldal
    title_translations:
      ro: Prima pagină
      en: Chapter ...Home...
      hu: Fejezet ...Kezdő oldal...
    content_translations:
      ro: Prima pagină
      en: Chapter ...Home...
      hu: Fejezet ...Kezdő oldal...
  knowledge_base:
    order: 2
    name_translations:
      ro: Generalităţi
      en: Knowledge base
      hu: Tudásalap
    title_translations:
      ro: Capitolul ...Generalităţi...
      en: Chapter ...Knowledge base...
      hu: Fejezet ...Tudásalap...
    content_translations:
      ro: Capitolul ...Generalităţi...
      en: Chapter ...Knowledge base...
      hu: Fejezet ...Tudásalap...
  methodology:
    order: 3
    name_translations:
      ro: Metodologie
      en: Methodolgy
      hu: Metodologia
    title_translations:
      ro: Capitolul ...Metodologie...
      en: Chapter ...Methodolgy...
      hu: Fejezet ...Metodologia...
    content_translations:
      ro: Capitolul ...Metodologie...
      en: Chapter ...Methodolgy...
      hu: Fejezet ...Metodologia...
  structure:
    order: 4
    name_translations:
      ro: Structura
      en: Structure
      hu: Struktúra
    title_translations:
      ro: Capitolul ...Structura...
      en: Chapter ...Structure...
      hu: Fejezet ...Struktúra...
    content_translations:
      ro: Capitolul ...Structura...
      en: Chapter ...Structure...
      hu: Fejezet ...Struktúra...
  glossary:
    order: 5
    name_translations:
      ro: Glosar
      en: Glossary
      hu: Fejezet ...Szójegyzék...
    title_translations:
      ro: Capitolul ...Glosar...
      en: Chapter ...Glossary...
      hu: Szójegyzék
    content_translations:
      ro: Capitolul ...Glosar...
      en: Chapter ...Glossary...
      hu: Fejezet ...Szójegyzék...
  about:
    order: 6
    name_translations:
      ro: Despre program
      en: About aplication
      hu: A program
    title_translations:
      ro: Capitolul ...Despre program...
      en: Chapter ...About aplication...
      hu: Fejezet ...A program...
    content_translations:
      ro: Capitolul ...Despre program...
      en: Chapter ...About aplication...
      hu: Fejezet ...A program...
trst_system:
  my_page:
    order: 1
    name_translations:
      ro: Pagina mea
      en: My page
      hu: Saját oldal
    title_translations:
      ro: Capitolul ...Pagina mea...
      en: Chapter ...My page...
      hu: Fejezet ...Saját oldal...
    content_translations:
      ro: Capitolul ...Pagina mea...
      en: Chapter ...My page...
      hu: Fejezet ...Saját oldal...
  modules:
    order: 2
    name_translations:
      ro: Module accesibile
      en: Modules avaible
      hu: Elérhető modulok
    title_translations:
      ro: Capitolul ...Module accesibile...
      en: Chapter ...Modules avaible...
      hu: Fejezet ...Elérhető modulok...
    content_translations:
      ro: Capitolul ...Module accesibile...
      en: Chapter ...Modules avaible...
      hu: Fejezet ...Elérhető modulok...
  settings:
    order: 3
    name_translations:
      ro: Setări
      en: Settings
      hu: Beállítások
    title_translations:
      ro: Capitolul ...Setări...
      en: Chapter ...Settings...
      hu: Fejezet ...Beállítások...
    content_translations:
      ro: Capitolul ...Setări...
      en: Chapter ...Settings...
      hu: Fejezet ...Beállítások...
  help:
    order: 4
    name_translations:
      ro: Help
      en: Help
      hu: Help
    title_translations:
      ro: Capitolul ...Help...
      en: Chapter ...Help...
      hu: Fejezet ...Help...
    content_translations:
      ro: Capitolul ...Help...
      en: Chapter ...Help...
      hu: Fejezet ...Help...
  sys_admin:
    order: 5
    name_translations:
      ro: TrustSys admin
      en: TrustSys admin
      hu: Rendszergazda
    title_translations:
      ro: Capitolul ...TrustSys admin...
      en: Chapter ...TrustSys admin...
      hu: Fejezet ...Rendszergazda...
    content_translations:
      ro: Capitolul ...TrustSys admin...
      en: Chapter ...TrustSys admin...
      hu: Fejezet ...Rendszergazda...
